### ISSUE TITLE
bug: Templates that depend on number-to-string coalescing do not compile in all languages

### ISSUE THREAD

**Issue by comcalvi** [cdklabs/cdk-from-cfn#615]
### Summary
In TS, templates that pass numbers where strings are expected causes a type error. This is arguably the right behavior, since the types don't match, but CFN allows passing `1` where `'1'` is expected.

The emitted Java code includes string literals that aren't properly escaped, or possibly just missing terminating / opening quotes. Not sure which.

CSharp does not like multi-line strings.

Go and Python are failing with type errors that are not obvious. 

Unclear if the number-to-string coalescing is the root cause of this for all languages, or if something else is happening.

### Reproduction Steps
1. Copy this JSON template: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-efs.html
2. Create a new end-to-end test that uses that template
3. `unset CREATE_CFN_STACK`
4. `cargo test --test end-to-end efs -- --nocapture`
5. 
```
failures:
    efs::csharp
    efs::golang
    efs::java
    efs::python
    efs::typescript
```

### TypeScript
Fails with
```
Type 'number' is not assignable to type 'string'.ts(2322)
```

This is caused by this code:

```
  public constructor(scope: cdk.App, id: string, props: EfsStackProps = {}) {
    super(scope, id, props);

    // Applying default props
    props = {
      ...props,
      // ... 
      asgMaxSize: props.asgMaxSize ?? 2, //   Type 'number' is not assignable to type 'string'.ts(2322)
    };
```

This is happening because in the JSON, we have:

```    
  "AsgMaxSize": {
      "Type": "Number",
      "Description": "Maximum size and initial desired capacity of Auto Scaling Group",
      "Default": "2"
    },
```

This is passed here:
```
    "AutoScalingGroup": {
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "Properties": {
        "MinSize": "1",
        "MaxSize": { "Ref": "AsgMaxSize" }, // MaxSize is a string property
```

It's debatable whether this is really a bug. `cdk-from-cfn` is doing the right thing, this only works because CFN allows you to pass a string where a number is expected. 

#### Java
Fails with unenclosed string literals:
```
java setup
cdk synth
[ERROR] COMPILATION ERROR : 
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[229,25] unclosed string literal
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[230,25] unclosed string literal
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[231,25] unclosed string literal
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[232,25] unclosed string literal
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[235,44] ';' expected
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[239,41] ';' expected
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[240,25] unclosed string literal
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[241,25] unclosed string literal
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[242,25] unclosed string literal
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[243,25] unclosed string literal
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[246,44] ';' expected
[ERROR] /Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-java-working-dir/src/main/java/com/myorg/Stack.java:[249,41] ';' expected
```

The errors are visible with syntax highlighting starting near line 254:

```
    launchConfiguration.addMetadata("AWS::CloudFormation::Init", Map.of("configSets", Map.of("MountConfig", Arrays.asList(
                "setup",
                "mount")),
        "setup", Map.of("packages", Map.of("yum", Map.of("nfs-utils", Arrays.asList(
        )),
        "files", Map.of("/home/ec2-user/post_nfsstat", Map.of("content", String.join("", // these opening parens are in red
                "#!/bin/bash
                ",
                "
                ",
                "INPUT="$(cat)"
                ",
                "CW_JSON_OPEN='{ "Namespace": "EFS", "MetricData": [ ' // highlighting is broken at this point
                ",
```

### Python
Fails with:

```
pip install
cdk synth

===== cdk synth stdout ===== END =======

===== cdk synth stderr ===== START =====
Traceback (most recent call last):
  File "/Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-python-working-dir/app.py", line 10, in <module>
    EfsStack(app, 'Stack')
  File "/Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-python-working-dir/.venv/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-python-working-dir/stack.py", line 409, in __init__
    image_id = awsRegionArch2Ami[self.region][awsInstanceType2Arch[props['instanceType']]['Arch']],
               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '${Token[AWS.Region.13]}'
```

No idea what causes this.

### CSharp
Doesn't like newlines appearing in string literals:

```
===== cdk synth stdout ===== START =====
/Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-csharp-working-dir/Stack.cs(328,21): error CS1010: Newline in constant [/Users/comcalvi/Documents/cdk-from-cfn/tests/end-to-end/efs-csharp-working-dir/CSharp.csproj]
/// ...
```

Caused by:
```
  var launchConfiguration = new CfnLaunchConfiguration(this, "LaunchConfiguration", new CfnLaunchConfigurationProps
            {
                AssociatePublicIpAddress = true,
                ImageId = awsRegionArch2Ami[Region][awsInstanceType2Arch[props.InstanceType]["Arch"]],
                InstanceType = props.InstanceType,
                SecurityGroups = new []
                {
                    instanceSecurityGroup.Ref,
                },
                IamInstanceProfile = cloudWatchPutMetricsInstanceProfile.Ref,
                UserData = Fn.Base64(string.Join("", new []
                {
                    "#!/bin/bash -xe // these are newlines in the literal
                    ",
                    "yum install -y aws-cfn-bootstrap
                    ",
                    "/opt/aws/bin/cfn-init -v ",
                    "         --stack ",
```

### Go
Fails with
```
===== cdk synth stderr ===== START =====
# command-line-arguments
./stack.go:308:20: cannot use &[]interface{}{…} (value of type *[]interface{}) as *[]*awsefs.CfnFileSystem_ElasticFileSystemTagProperty value in struct literal
./stack.go:309:6: undefined: ElasticFileSystemTagProperty
./stack.go:410:6: undefined: IngressProperty
./stack.go:416:6: undefined: IngressProperty
```

It's mad about this code:

```

	fileSystem := efs.NewCfnFileSystem(
		stack,
		jsii.String("FileSystem"),
		&efs.CfnFileSystemProps{
			PerformanceMode: jsii.String("generalPurpose"),
			FileSystemTags: &[]interface{}{
				&ElasticFileSystemTagProperty{
					Key: jsii.String("Name"),
					Value: props.VolumeName,
				},
			},
		},
	)
```

**Comment by TheRealAmazonKendra** [comment]
I forgot to write a ticket for this but I actually have a fix in progress.
